package main

import "time"

type AutoGenerated struct {
	EventID      string `json:"event_id"`
	EventType    string `json:"event_type"`
	FormResponse struct {
		FormID      string    `json:"form_id"`
		Token       string    `json:"token"`
		LandedAt    time.Time `json:"landed_at"`
		SubmittedAt time.Time `json:"submitted_at"`
		Definition  struct {
			ID     string `json:"id"`
			Title  string `json:"title"`
			Fields []struct {
				ID         string `json:"id"`
				Title      string `json:"title"`
				Type       string `json:"type"`
				Ref        string `json:"ref"`
				Properties struct {
				} `json:"properties"`
				AllowMultipleSelections bool `json:"allow_multiple_selections,omitempty"`
				Choices                 []struct {
					ID    string `json:"id"`
					Label string `json:"label"`
				} `json:"choices,omitempty"`
			} `json:"fields"`
		} `json:"definition"`
		Answers []struct {
			Type        string `json:"type"`
			PhoneNumber string `json:"phone_number,omitempty"`
			Field       struct {
				ID   string `json:"id"`
				Type string `json:"type"`
				Ref  string `json:"ref"`
			} `json:"field"`
			Text    string `json:"text,omitempty"`
			Choices struct {
				Labels []string `json:"labels"`
			} `json:"choices,omitempty"`
			Boolean bool `json:"boolean,omitempty"`
		} `json:"answers"`
	} `json:"form_response"`
}
